/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.mit.ll.mitie;

public class TextCategorizer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TextCategorizer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TextCategorizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        globalJNI.delete_TextCategorizer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TextCategorizer(String pureModelName, String extractorName) {
    this(globalJNI.new_TextCategorizer__SWIG_0(pureModelName, extractorName), true);
  }

  public TextCategorizer(String pureModelName) {
    this(globalJNI.new_TextCategorizer__SWIG_1(pureModelName), true);
  }

  public StringVector getPossibleNerTags() {
    return new StringVector(globalJNI.TextCategorizer_getPossibleNerTags(swigCPtr, this), true);
  }

  public void saveToDisk(String filename) {
    globalJNI.TextCategorizer_saveToDisk(swigCPtr, this, filename);
  }

  public SDPair categorizeDoc(StringVector words, TotalWordFeatureExtractor extractorObject) {
    return new SDPair(globalJNI.TextCategorizer_categorizeDoc(swigCPtr, this, StringVector.getCPtr(words), words, TotalWordFeatureExtractor.getCPtr(extractorObject), extractorObject), true);
  }

}
