/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.mit.ll.mitie;

public class TextCategorizerTrainer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TextCategorizerTrainer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TextCategorizerTrainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        globalJNI.delete_TextCategorizerTrainer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TextCategorizerTrainer() {
    this(globalJNI.new_TextCategorizerTrainer(), true);
  }

  public void add(StringVector words, String label) {
    globalJNI.TextCategorizerTrainer_add(swigCPtr, this, StringVector.getCPtr(words), words, label);
  }

  public void setThreadNum(long num) {
    globalJNI.TextCategorizerTrainer_setThreadNum(swigCPtr, this, num);
  }

  public void setEnableTuningClassifier(boolean enabler) {
    globalJNI.TextCategorizerTrainer_setEnableTuningClassifier(swigCPtr, this, enabler);
  }

  public void trainSeparateModels(TotalWordFeatureExtractor extractorObject, String filename) {
    globalJNI.TextCategorizerTrainer_trainSeparateModels(swigCPtr, this, TotalWordFeatureExtractor.getCPtr(extractorObject), extractorObject, filename);
  }

}
